### ISSUE TITLE
Failed creating a mirror pod...connection refused

### ISSUE THREAD

**Issue by nbs-jeanpierrefouche** [abstractinfrastructure/k8s-gcr-quickfix#3]
After installing using helm I get: 

**Failed creating a mirror pod**

`
>ip-172-20-114-144 /home/core # journalctl -efx
Failed creating a mirror pod for "kube-proxy-ip-172-20-114-144.eu-west-2.compute.internal_kube-system(be626a0cf52acb592e944834fa66ec21)": Internal error occurred: failed calling webhook "mutate.kyverno.svc-fail": Post "https://kyverno-svc.kyverno.svc:443/mutate/fail?timeout=10s": dial tcp 100.71.82.136:443: connect: connection refused`

I am using kops v1.19.3 --> unsupported.  Do you possibly have any ideas to help?
Many Thanks

**Comment by jeefy** [comment]
This project doesn't use Helm. Do you mean you installed Kyverno using Helm? If so, you might want to create an issue over in the [Kyverno repo](https://github.com/kyverno/kyverno). 

I don't see anything wrong specific to this project, so I'm going to close this. If there's more information that is specific to the quickfix, please re-open and post.
